//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarouselCellType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarouselCellType.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Binding Settings.
        /// </summary>
        public static string BindingImageEditor_ImageBindingSettings {
            get {
                return ResourceManager.GetString("BindingImageEditor_ImageBindingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptionColumn:.
        /// </summary>
        public static string BindingImagesEditor_CaptionColumnLabel {
            get {
                return ResourceManager.GetString("BindingImagesEditor_CaptionColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionColumn:.
        /// </summary>
        public static string BindingImagesEditor_DescriptionColumnLabel {
            get {
                return ResourceManager.GetString("BindingImagesEditor_DescriptionColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image column can&apos;t be empty..
        /// </summary>
        public static string BindingImagesEditor_ImageColumnCantBeEmpty {
            get {
                return ResourceManager.GetString("BindingImagesEditor_ImageColumnCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageColumn:.
        /// </summary>
        public static string BindingImagesEditor_ImageColumnLabel {
            get {
                return ResourceManager.GetString("BindingImagesEditor_ImageColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectTable:.
        /// </summary>
        public static string BindingImagesEditor_SelectTableLabel {
            get {
                return ResourceManager.GetString("BindingImagesEditor_SelectTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name can&apos;t be empty..
        /// </summary>
        public static string BindingImagesEditor_TableNameCantBeEmpty {
            get {
                return ResourceManager.GetString("BindingImagesEditor_TableNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Slide.
        /// </summary>
        public static string CarouselCellType_AutoSlide {
            get {
                return ResourceManager.GetString("CarouselCellType_AutoSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image{0}.
        /// </summary>
        public static string CarouselCellType_DefaultImageName {
            get {
                return ResourceManager.GetString("CarouselCellType_DefaultImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string CarouselCellType_DisplayName {
            get {
                return ResourceManager.GetString("CarouselCellType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Commands....
        /// </summary>
        public static string CarouselCellType_EditCommands {
            get {
                return ResourceManager.GetString("CarouselCellType_EditCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Image Infos....
        /// </summary>
        public static string CarouselCellType_EditImageInfos {
            get {
                return ResourceManager.GetString("CarouselCellType_EditImageInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageInfo Settings.
        /// </summary>
        public static string CarouselCellType_ImageInfoSettings {
            get {
                return ResourceManager.GetString("CarouselCellType_ImageInfoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string CarouselCellType_Interval {
            get {
                return ResourceManager.GetString("CarouselCellType_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the delay (in seconds) between each slide..
        /// </summary>
        public static string CarouselCellType_IntervalDescription {
            get {
                return ResourceManager.GetString("CarouselCellType_IntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBinding.
        /// </summary>
        public static string CarouselCellType_IsBinding {
            get {
                return ResourceManager.GetString("CarouselCellType_IsBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string CarouselCellType_Options {
            get {
                return ResourceManager.GetString("CarouselCellType_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PauseWhenHover.
        /// </summary>
        public static string CarouselCellType_PauseWhenHover {
            get {
                return ResourceManager.GetString("CarouselCellType_PauseWhenHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the carousel from going through the next slide when the mouse pointer enters the carousel, and resumes the sliding when the mouse pointer leaves the carousel..
        /// </summary>
        public static string CarouselCellType_PauseWhenHoverDescription {
            get {
                return ResourceManager.GetString("CarouselCellType_PauseWhenHoverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show caption and description.
        /// </summary>
        public static string CarouselCellType_ShowDescriptionText {
            get {
                return ResourceManager.GetString("CarouselCellType_ShowDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowIndicators.
        /// </summary>
        public static string CarouselCellType_ShowIndicators {
            get {
                return ResourceManager.GetString("CarouselCellType_ShowIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowLeftRightControls.
        /// </summary>
        public static string CarouselCellType_ShowLeftRightControls {
            get {
                return ResourceManager.GetString("CarouselCellType_ShowLeftRightControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap.
        /// </summary>
        public static string CarouselCellType_Wrap {
            get {
                return ResourceManager.GetString("CarouselCellType_Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the carousel should go through all slides continuously, or stop at the last slide..
        /// </summary>
        public static string CarouselCellType_WrapDescription {
            get {
                return ResourceManager.GetString("CarouselCellType_WrapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ImagesEditor_AddImageToolTip {
            get {
                return ResourceManager.GetString("ImagesEditor_AddImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption:.
        /// </summary>
        public static string ImagesEditor_CaptionLabel {
            get {
                return ResourceManager.GetString("ImagesEditor_CaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Settings.
        /// </summary>
        public static string ImagesEditor_CommandsSettings {
            get {
                return ResourceManager.GetString("ImagesEditor_CommandsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ImagesEditor_DeleteImageToolTip {
            get {
                return ResourceManager.GetString("ImagesEditor_DeleteImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string ImagesEditor_DescriptionLabel {
            get {
                return ResourceManager.GetString("ImagesEditor_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string ImagesEditor_DownImageToolTip {
            get {
                return ResourceManager.GetString("ImagesEditor_DownImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Commands....
        /// </summary>
        public static string ImagesEditor_EditCommands {
            get {
                return ResourceManager.GetString("ImagesEditor_EditCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will trigger command when you click image..
        /// </summary>
        public static string ImagesEditor_EditCommandsToolTip {
            get {
                return ResourceManager.GetString("ImagesEditor_EditCommandsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path:.
        /// </summary>
        public static string ImagesEditor_ImagePathLabel {
            get {
                return ResourceManager.GetString("ImagesEditor_ImagePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Settings.
        /// </summary>
        public static string ImagesEditor_PropertiesSettings {
            get {
                return ResourceManager.GetString("ImagesEditor_PropertiesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image....
        /// </summary>
        public static string ImagesEditor_SelectImage {
            get {
                return ResourceManager.GetString("ImagesEditor_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string ImagesEditor_UpImageToolTip {
            get {
                return ResourceManager.GetString("ImagesEditor_UpImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainWindow_CancelButtonText {
            get {
                return ResourceManager.GetString("MainWindow_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MainWindow_OKButtonText {
            get {
                return ResourceManager.GetString("MainWindow_OKButtonText", resourceCulture);
            }
        }
    }
}
